app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/


Route::get('/test', function () {
    $post=\App\Post::findOrfail(29);
    var_dump($post);
    \App\FbApi\Fb::loadResources($post);
});


Route::group(['prefix' => 'api','middleware' => 'web'], function()
{
    Route::resource('/pages', 'PageController');
    Route::resource('/access_tokens', 'TokenController');
    Route::resource('/apps', 'FAppController');
    Route::resource('/posts', 'PostController');
    Route::get('/scrap','ScrapingController@scrap');
});

Route::group(['middleware' => 'web'], function () {

    Route::auth();
    //Route::get('/home', 'HomeController@index');
    Route::get('/', 'HomeController@index');

    Route::resource('/access_tokens', 'TokenController');

    Route::resource('/apps', 'FAppController');
    Route::resource('/posts', 'PostController');
    Route::get('/scraping','ScrapingController@index');



});

app/Token.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Token extends Model
{
    protected  $table="tokens";
    protected $fillable = [
        'name', 'text', 'app_id','page_id',
    ];

    public function page()
    {
        return $this->belongsTo('\App\Page');
    }
    public function app()
    {
        return $this->belongsTo('\App\FApp');
    }

    public function scopeToscrap($query){
        return $query->where('page_id','0');
    }
}

app/Http/Controllers/TokenController.php
<?php

namespace App\Http\Controllers;


use App\Token;

use App\Http\Requests\TokenRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;

class TokenController extends Controller
{


    public function index()
    {
        $tokens = Token::all();
        return $tokens;
    }
    public function store(TokenRequest $token)
    {
            $t=Token::create($token->all());
            return response()->json($t);
    }

    public function update($id,TokenRequest $t)
    {
        $token= Token::findOrfail($id);
        $token->update($t->all());
    }

    public function destroy($id)
    {
        Token::destroy($id);
    }

}

resources/views/tokens/_form.blade.php
@if (count($errors) > 0)
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
            </button>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
<div class="form-group">
    {!! Form::label('name','Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control','placeholder'=>'access Token Title']) !!}
</div>
<div class="form-group">
    {!! Form::label('text', 'Access Token:') !!}
    {!! Form::text('text', null, ['class' => 'form-control','placeholder'=>'access Token Text']) !!}
</div>
<div class="form-group">
    {!! Form::label('Facebook App', 'Facebook App:') !!}
    {!! Form::select('app_id', \App\FApp::lists('name','id'), null, ['class'=>'form-control'])!!}
</div>
    <div class="form-group">
        {!! Form::label('Facebook page', 'Facebook Page:') !!}
        {!! Form::select('page_id', \App\Page::lists('name','id'), null, ['class'=>'form-control','placeholder'=>'token to scrap'])!!}
    </div>

{!!Form::submit($text,['class'=>'btn btn-info pull-right '])!!}

resources/views/tokens/create.blade.php
@extends('layouts.app2')

@section('content')
    <div class="row panel panel-footer">
        <br/>
        <div class="col-md-12 pull-center">
        {!! Form::model(new \App\Token,['route' => 'access_tokens.store']) !!}
            @include('tokens/_form', ['text' => 'Create Token'])
        {!! Form::close() !!}
    </div>
    </div>
@endsection

resources/views/tokens/edit.blade.php
@extends('layouts.app2')

@section('content')
    <div class="row panel panel-footer">
        <br/>
        <div class="col-md-12 pull-center">
            {!! Form::model($token,['method'=>'put' , 'url'=>route('access_tokens.update',$token)]) !!}
            @include('tokens/_form', ['text' => 'update Token'])
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/tokens/tokens.blade.php
@extends('layouts.app2')

@section('content')
    <div class="row">

        <div class="x_panel">
            <div class="x_title">
                <h2>All Access Tokens </h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>title</th>
                        <th>text</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($tokens as $token)
                    <tr>
                        <th scope="row">{{$token->id}}</th>
                        <td>{{$token->name}}</td>
                        <td style="max-width: 300px;overflow: scroll"><span>{{$token->text}}</span></td>
                        <td width="180px">

                            <a href="{{url("/access_tokens/$token->id/edit")}}" class="left"><span class=" fa fa-3x fa-edit  "></span></a>
                                {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('access_tokens.destroy', $token->id))) !!}
                                <button type="submit" class="fa fa-2x fa-remove btn-danger"></button>
                                {!! Form::close() !!}


                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>
@endsection