app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/


Route::get('/test', function () {
    $post=\App\Post::findOrfail(29);
    var_dump($post);
    \App\FbApi\Fb::loadResources($post);
});


Route::group(['prefix' => 'api','middleware' => 'web'], function()
{
    Route::resource('/pages', 'PageController');
    Route::resource('/access_tokens', 'TokenController');
    Route::resource('/apps', 'FAppController');
    Route::resource('/posts', 'PostController');
    Route::get('/scrap','ScrapingController@scrap');
});

Route::group(['middleware' => 'web'], function () {

    Route::auth();
    //Route::get('/home', 'HomeController@index');
    Route::get('/', 'HomeController@index');

    Route::resource('/access_tokens', 'TokenController');

    Route::resource('/apps', 'FAppController');
    Route::resource('/posts', 'PostController');
    Route::get('/scraping','ScrapingController@index');



});

resources/views/pages/_form.blade.php
@if (count($errors) > 0)
<div class="alert alert-danger alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
    </button>
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="form-group">
    {!! Form::label('name','Page Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control','placeholder'=>'your page name']) !!}
</div>
<div class="form-group">
    {!! Form::label('page_id', 'page Id:') !!}
    {!! Form::text('page_id', null, ['class' => 'form-control','placeholder'=>'your page id']) !!}
</div>


{!!Form::submit($text,['class'=>'btn btn-info pull-right '])!!}

resources/views/pages/create.blade.php
@extends('layouts.app2')
@section('content')
    <div class="row panel panel-footer">
        <br/>
        <div class="col-md-12 pull-center">
            {!! Form::model(new \App\Page,['route' => 'pages.store']) !!}
            @include('pages/_form', ['text' => 'Create Page'])
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.app2')

@section('content')
    <div class="row panel panel-footer">
        <br/>
        <div class="col-md-12 pull-center">
            {!! Form::model($page,['method'=>'put' , 'url'=>route('pages.update',$page)]) !!}
            @include('pages/_form', ['text' => 'update Page'])
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/pages/pages.blade.php
@extends('layouts.app2')

@section('content')
    <div class="row">

        <div class="x_panel">
            <div class="x_title">
                <h2> All Pages </h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>name</th>
                        <th>page id</th>
                        <th>page Access Token </th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($pages as $page)
                        <tr>
                            <th scope="row">{{$page->id}}</th>
                            <td>{{$page->name}}</td>
                            <td>{{$page->page_id}}</td>
                            <td>

                            </td>
                            <td width="180px">

                                <a href="{{url("/pages/$page->id/edit")}}" class="left"><span class=" fa fa-3x fa-edit  "></span></a>
                                {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('pages.destroy', $page->id))) !!}
                                <button type="submit" class="fa fa-2x fa-remove btn-danger"></button>
                                {!! Form::close() !!}


                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>
@endsection